### ISSUE TITLE
Fix AutoPytorch Regression

### ISSUE THREAD

**Issue by al-becker** [hochschule-darmstadt/MetaAutoML#41] opened 2022-01-12 10:43 UTC

**Comment by SpaceDave42** [comment] 2022-01-25 07:51
This is a Bug with Auto-PyTorch as of version 0.1.1. It is mentioned in this issue [#352](https://github.com/automl/Auto-PyTorch/issues/352) on the Auto-PyTorch github and while there is a PR with a fix open it has not been merged yet.
The bug appears on initialization with some regression datasets and is caused by wrongful initialization of PyTorch by the Auto-PyTorch wrapper.

As soon as the fix is merged Auto-PyTorch (should) work again.

**Closed** 2022-10-18 10:22 UTC
Labels: bug, backend
