### ISSUE TITLE
Training Wizard

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/MetaAutoML#165] opened 2022-10-18 11:05 UTC
TODO: specify

**Reason (Why?)**
Why do you want this feature? What goals should be achieved? Is your issue related to a problem?

**Solution (What?)**
Describe the suggested solution (Don't repeat the reason again)

**Out of scope**
Anything that is out of scope and shall not be implemented

**Relation to other Issues**
Provide additional context (link relevant issues)

**Acceptance criteria**
Describe acceptance criteria for testing (Don't repeat reason and solution again)

**Comment by zavog** [comment] 2022-11-07 19:43
Sketch of the UI:

![ui sketch](https://user-images.githubusercontent.com/51450061/200399903-4cf9e496-61ec-4faa-a7d8-2bb2afb0ddd9.jpeg)

**Comment by zavog** [comment] 2022-11-07 21:04
Idea 1: One query to find everything for the given ml_task, where the results then have to be filtered in code. Example for tabular classification:

```sparql
PREFIX : <http://h-da.de/ml-ontology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?automl ?param ?param_label ?param_type ?value ?value_label
WHERE {
  ?automl a :AutoML_solution ;
          :supported_by_oma_ml "True" .
  ?ci a :Configuration_item ;
      :category :task_configuration ;
      :automl_solution ?automl ;
      :ml_task :tabular_classification ;
      :parameter_value ?param .
  ?param :parameter_value ?value ;
         skos:prefLabel ?param_label ;
         :has_datatype ?param_type .
  ?value skos:prefLabel ?value_label .
}
```

Idea 2: 1 Query for each auto ml solution.

Idea 3: Generate Query at runtime that only finds the relevant configuration items. Example for query with autosklearn and autokeras:

```sparql
PREFIX : <http://h-da.de/ml-ontology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?automl ?param ?param_label ?param_type ?value ?value_label
WHERE {
  { ?ci a :Configuration_item ;
        :automl_solution :autosklearn }
  UNION
  { ?ci a :Configuration_item ;
        :automl_solution :autokeras }
  
  ?ci a :Configuration_item ;
      :category :task_configuration ;
      :automl_solution ?automl ;
      :ml_task :tabular_classification ;
      :parameter_value ?param .
  ?param :parameter_value ?value ;
         skos:prefLabel ?param_label ;
         :has_datatype ?param_type .
  ?value skos:prefLabel ?value_label .
}
```

I would choose option 2 for now, because it is the simplest

**Comment by zavog** [comment] 2022-11-07 22:02
Added the query, but it isn't called yet by anyone.

**Comment by zavog** [comment] 2022-11-13 09:14
@AlexanderZender The step I had to do in [this commit](https://github.com/hochschule-darmstadt/MetaAutoML/commit/73a2375c276ee348e056894c7f48816adc3e6197) was not documented in the explanation on how to adapt the gRPC interface. I think it's worth adding that there. Should I open an issue for that?

**Comment by zavog** [comment] 2022-11-13 10:42
Initial query now works. The way it is shown is awkward, but it does show results.
Problem: The way this page is implemented causes it to send lots of requests. The whole logic is triggered by UI events and each mutation of the list of MlSolutions fires an event. Maybe something like the MVVM pattern could be used to resolve this.

**Comment by BernhardHumm** [comment] 2022-11-14 09:57
If there are no performance problems there is no need for performance 
optimization.

**Comment by AlexanderZender** [comment] 2022-11-14 12:33
> @AlexanderZender The step I had to do in [this commit](https://github.com/hochschule-darmstadt/MetaAutoML/commit/73a2375c276ee348e056894c7f48816adc3e6197) was not documented in the explanation on how to adapt the gRPC interface. I think it's worth adding that there. Should I open an issue for that?

Yea it is worth adding, a new issue would be great!

**Comment by zavog** [comment] 2022-11-14 20:50
> If there are no performance problems there is no need for performance optimization.

I agree, but here the problem is not performance related. Unfortunately it's a race condition. All event handlers are non-blocking and when a library is deselected, multiple auto ml solutions can be deselcted as well. In such a case the event handler will be triggered as many times as the number of removed auto ml solutions almost simultaneously and send a request. The slowest request will win and set the list of available parameters. Unfortunately the slowest request is usually the one where the most solutions were still selected. => The parameters will look like only one solution was deselected instead of multiple.

**Comment by zavog** [comment] 2022-11-23 23:36
Refactoring is complete. Race condition is resolved.

Added a new component for chipset and introduced a ViewModel for it. The only logic that is triggerred by UI-Events now is that the selection of a chip is toggled on click. Everything else responds to notifications from the view models.

Previous control flow:

1. User clicks on library
2. UI-Event: selection changed
3. Event handler loads solutions
4. UI updates => UI-Event (x times)
5. Event handler loads parameters (x times)
6. UI updates (x times)

Control flow now:

1. User clicks on library
2. UI-Event: selection changed
3. Libraries ViewModel updates state -> Event
4. EventHandler loads solutions and updates Solutions ViewModel -> Event
5. EventHandler loads parameters
6. UI updates (once)

Also extracted the handling of ApiResponses and used the more typesafe methods for the requests

**Comment by zavog** [comment] 2022-11-24 10:45
After a brief discussion in our weekly meeting, we came to the conclusion that the refactoring should be merged. For this to possible, a new branch must be created that contains the refactoring improvements, but not the WIP state of the parameters

**Comment by zavog** [comment] 2022-11-24 11:02
# Definition of the API

## API

The Dto should receive a new parameter called "Parameters". The DTO then looks like the following:

```csharp
public class Dto
{
  // ...
  public Dictionary<string, List<object>> Parameters { get; set; }
}
```

An example json looks like the following:

```json
{
  // ...
  "parameters": {
    ":use_approach": [ ":adaboost", ":decision_tree"],
    ":metric": [ ":f1"]
  }
}
```

## Reasons

List was chosen as datatype for each parameter, because it works in all cases and makes intersecting parameters easier, if one solution has the type list while another one expects single_value:

- single string: `["the text"]`
- single number: `[ 1 ]`
- multiple values: `[ "a", "b" ]`

## Decisions for future extension

At a later point, when solution specific configuration will be added, we'll send all parameters to all adapters and the adapters will have to handle the fact that the list of parameters they receive contains parameters that they do not support.

## Next Steps

1. Implement intersection of parameters
2. Implement UI to show the intersected parameters
3. Update communication interfaces
    1. Frontend client to frontend server
    2. frontend server to controller (gRPC)
    3. controller to adapter
4. Send entered configuration

**Comment by zavog** [comment] 2022-12-15 00:02
Calculation of the intersected parameters is complete.

Parameters that are not shown due to the intersection are shown after the intersection. Parameters are also shown, when the type determined for the intersection is more restrictive than the actual type (:single_value instead of :list). The implementation of these "individual" parameters needs refactoring, because it is not very readable.

Additionally configuration of parameters for each individual solution may be wanted when less selection options were available in the intersected part. In any case: When a parameter is shown in the intersected area and in the individual area, the user should not be offered value options in the individual area that they already selected in the intersected area.

Should the time_limit parameter be removed from the ontology, or should the UI specifically ignore this parameter?

**Comment by zavog** [comment] 2022-12-18 13:39
> I would leave time_limit in the ontology since it reflects exactly the capabilities of the respective AutoML APIs (some offer a time limit parameter, others don’t)

Ok, then we'll filter out the time limit parameters in the query.

The "parameters" property has been added to the gRPC requests, but it is always an empty list so far (The input from the UI is not transferred to the requestDto yet). Next step: Fill the parameters list in the frontend. After that we can let the AutoSkLearn adapter team know that they can receive parameters now.

**Closed** 2023-01-24 07:23 UTC
Labels: frontend, ontology
